{% set name = "mag2exp" %}
{% set version = "0.62.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 631a5f3cc29e0f667f23dbc79018709d9fbc5b77a0c9bb55cd1b6ab7911608a0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - oommfc >=0.63.0
    - numpy >=1.19
    - scipy >=1.6

test:
  imports:
    - mag2exp
  commands:
    - python -c "import sys; import mag2exp; sys.exit(mag2exp.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simulate experimental measurements for magnetic materials.
  doc_url: https://ubermag.github.io/documentation/mag2exp.html
  dev_url: https://github.com/ubermag/mag2exp

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
