{% set name = "mag2exp" %}
{% set version = "0.62.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6cbd4c9c82300305fe9a13abb5827e8c4ad47412f1e7018899c1bac1e5276d3b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - oommfc >=0.64.1
    - numpy >=1.19
    - scipy >=1.6

test:
  imports:
    - mag2exp
  commands:
    - python -c "import sys; import mag2exp; sys.exit(mag2exp.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simulate experimental measurements for magnetic materials.
  doc_url: https://ubermag.github.io/documentation/mag2exp.html
  dev_url: https://github.com/ubermag/mag2exp

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
