{% set name = "mag2exp" %}
{% set version = "0.61.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e663bc466ac30f07548e96e37b1921361f40141380ef013db6d6b95098c579f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - oommfc ==0.61.*
    - numpy >=1.19
    - scipy >=1.6

test:
  imports:
    - mag2exp
  commands:
    - python -c "import sys; import mag2exp; sys.exit(mag2exp.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simulate experimental measurements for magnetic materials.
  doc_url: https://ubermag.github.io/documentation/mag2exp.html
  dev_url: https://github.com/ubermag/mag2exp

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
