{% set name = "mag2exp" %}
{% set version = "0.63.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 06daab8162c78d95591c6feb017e693dd838d10a6d874ded9d2e2d23c26e9891

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - oommfc >=0.65.0
    - numpy >=1.19
    - scipy >=1.6

test:
  requires:
    - python {{ python_min }}
  imports:
    - mag2exp
  commands:
    - python -c "import sys; import mag2exp; sys.exit(mag2exp.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simulate experimental measurements for magnetic materials.
  doc_url: https://ubermag.github.io/documentation/mag2exp.html
  dev_url: https://github.com/ubermag/mag2exp

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
